### PR TITLE
Merge wip/sbt-2.x-temp and origin/main into wip/sbt-2.x

### PR DESCRIPTION
**Pull request by adpi2**
And update librarymanagement to https://github.com/sbt/librarymanagement/pull/442

### CODE REVIEW

**Comment by adpi2** [comment]
~~Hey @eed3si9n it seems there is some code in [librarymanagement-coursier:2.0.0-alpha7](https://index.scala-lang.org/eed3si9n/sbt-coursier/artifacts/librarymanagement-coursier/2.0.0-alpha7) that is not in your `wip/sbt-2.x` branch. Could you please push it or point me to it?~~

~~I am trying to run the tests in https://github.com/sbt/sbt/pull/7573 to validate https://github.com/sbt/librarymanagement/pull/442 and https://github.com/eed3si9n/sbt-coursier/pull/1.~~

**Comment by adpi2** [comment]
@eed3si9n This is ready for review.

Also I published a snapshot version of it which is used in https://github.com/sbt/sbt/pull/7554

**Comment by adpi2** [comment]
Actually there is still something wrong with shading:
```
[error] (scalaCompilerBridgeBinaryJar) java.lang.NoClassDefFoundError: lmcoursier/internal/shaded/scala/collection/compat/immutable/package$
```

**Comment by adpi2** [comment]
@eed3si9n It's ready again

**Review by eed3si9n — APPROVED** [review]

**Comment by eed3si9n** [comment]
Not sure what's starting Mima here

```
[info] loading settings for project sbt-coursier-root from build.sbt ...
[info] resolving key references (13375 settings) ...
error: malformed object name v2.0.0-RC3-6
error: malformed object name v2.0.0-RC3-6
java.lang.RuntimeException: Nonzero exit value: 129
	at scala.sys.package$.error(package.scala:30)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:138)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:108)
	at Mima$.binaryCompatibilityVersions(Mima.scala:17)
	at Mima$.$anonfun$settings$1(Mima.scala:28)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:229)
	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:171)
	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:88)
	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:100)
	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:95)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Pull request merged**
